### ISSUE TITLE
How to clear webview cookies

### ISSUE THREAD

**Issue by gkye** [leonbreedt/OAuth2#3]
Im unable to clear to cookies from the webview for some strange reason (attempting to implement a logout function). I've set `OAuth2.loggingEnabled = false` and tried deleting the cookies many different ways but none of the methods tried seems to work, the webview automatically logs the previous user in each time.

**Attempt 1**

``` swift
     let storage =  NSHTTPCookieStorage.sharedHTTPCookieStorage()
        for cookie in storage.cookies!{
            cookie.delete(self)
        }
```

**Attempt 2**

``` swift
  let storage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
        storage.cookies?.forEach() { storage.deleteCookie($0) }
```

**Attempt 3**

``` swift
var libraryPath = NSSearchPathForDirectoriesInDomains(NSSearchPathDirectory.LibraryDirectory, NSSearchPathDomainMask.UserDomainMask, false).first!
libraryPath += "/Cookies"

do {
  let result = try NSFileManager.defaultManager().removeItemAtPath(libraryPath)
  print(result)
} catch {
  print("error")
}
NSURLCache.sharedURLCache().removeAllCachedResponses()
```

**Comment by bitserf** [comment]
Hello George,

This is odd, I use `NSURLSessionConfiguration.defaultConfiguration()`, which should be using the same shared cookie store as `NSHTTPCookieStorage.sharedHTTPCookieStorage()`.

Have you tried calling `NSUserDefaults.standardUserDefaults().synchronize()` after deleting the cookies? Shouldn't be necessary, but I've seen a post on StackOverflow claiming this is required to flush the changes to disk.

Anyhow, it seems useful to let you as the caller control the NSURLSession, so I think I will add a property that allows you to access the NSURLSession that I use, as well as letting you provide your own NSURLSession to the library, which would allow you to call this, which looks more correct:

https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/resetWithCompletionHandler:

Thanks for the report
Leon

**Comment by bitserf** [comment]
Also, since you're talking about webview cookies, and Apple makes life harder with `WKWebView` (while in theory it uses the default cookie storage), could you try some of the suggestions here?

https://github.com/ShingoFukuyama/WKWebViewTips

If you want to access the `WKWebView` directly, you can inherit from `WebViewController`, and inject your custom controller by passing through a closure that creates it in the `createWebViewController:` parameter of the `OAuth2.authorize()` method.

**Comment by gkye** [comment]
I finally got it work by following this tip https://github.com/ShingoFukuyama/WKWebViewTips#cookie-cache-credential-webkit-data-cannot-easily-delete.

```swift
        let websiteDataTypes: NSSet = [  WKWebsiteDataTypeDiskCache,
        WKWebsiteDataTypeOfflineWebApplicationCache,
        WKWebsiteDataTypeMemoryCache,
        WKWebsiteDataTypeLocalStorage,
        WKWebsiteDataTypeCookies,
        WKWebsiteDataTypeSessionStorage,
        WKWebsiteDataTypeIndexedDBDatabases,
        WKWebsiteDataTypeWebSQLDatabases
        ];
        let dateFrom: NSDate = NSDate(timeIntervalSince1970: 0)
        WKWebsiteDataStore.defaultDataStore().removeDataOfTypes(websiteDataTypes as! Set<String>, modifiedSince: dateFrom, completionHandler: {() -> Void in
            // Done
        })
        NSUserDefaults.standardUserDefaults().synchronize()
```
I highly doubt that the easiest way (but it works lool).
PS. Direct access to the `NSURLSession` being used with be great.
Thanks for your help Leon!

**Comment by bitserf** [comment]
Instead of direct NSURLSession access, I've made available the `NSURLSession` configuration to use, as well as the `WKWebView` configuration to use, via `OAuth2.urlSessionConfiguration` and `OAuth2.webViewConfiguration` properties.

I also changed the defaults:

- NSURLSession now uses an _ephemeral_ session configuration, since for an authentication library I think it is better not to store or share cookies.
- WKWebView now uses a _non-persistent_ WKWebsiteDataStore.

So by default, you may be getting the logout behaviour you desire. But since you can control the session & web view configuration, you can make it use the cookie storage behaviour that works for your app.
